version: '2'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        links:
            - 'postgres:database'
            - 'prisma:prisma'
            - 'mongodb:mongodb'
            - 'redis:redis'
        ports:
            - '4001:4000'
        environment:
            PRISMA_SECRET: $PRISMA_SECRET
            PRISMA_MANAGEMENT_API_SECRET: $PRISMA_MANAGEMENT_API_SECRET
            PRISMA_ENDPOINT: $PRISMA_ENDPOINT
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_PORT: $POSTGRES_PORT
            POSTGRES_HOST: database
            MONGODB_HOST: $MONGODB_HOST
            MONGODB_PORT: $MONGODB_PORT
            NODE_ENV: production
        depends_on:
            - postgres
            - pgadmin
            - mongodb
            - prisma
            - redis
        networks:
            - uxbackend_network
        volumes:
            - './data/config:/app/src/config'
            - './data/uploads:/app/uploads'
            - './data/prisma:/app/prisma'
            - './data/logs:/app/logs'
    mongodb:
        image: 'mongo:latest'
        restart: always
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        networks:
            - uxbackend_network
        volumes:
            - './data/mongodb:/data/db'
        #ports:
        #- '27017:27017'
        command: 'mongod --smallfiles --logpath=/dev/null'
    postgres:
        image: 'postgres:latest'
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            PGDATA: /data/postgres
        restart: always
        #ports:
        #- "5432:5432"
        volumes:
            - './data/postgres:/data/postgres'
        networks:
            - uxbackend_network
    pgadmin:
        image: fenglc/pgadmin4
        links:
            - 'postgres:postgres'
        depends_on:
            - postgres
        volumes:
            - './data/pgadmin:/root/.pgadmin'
        restart: always
        #ports:
        #- '5052:5050'
        networks:
            - uxbackend_network
        environment:
            DEFAULT_USER: $PGADMIN_DEFAULT_USER
            DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    redis:
        image: redis:latest
        restart: always
        #ports:
        #- "6379:6379"
        networks:
            - uxbackend_network
        volumes:
            - ./data/redis:/data
    prisma:
        image: prismagraphql/prisma:1.26.6
        restart: always
        networks:
            - uxbackend_network
        ports:
            - "4488:4466"
        depends_on:
            - postgres
        links:
            - 'postgres:postgres'
        environment:
            PRISMA_CONFIG: |
                managementApiSecret: $PRISMA_MANAGEMENT_API_SECRET
                port: 4466
                databases:
                    default:
                        connector: postgres
                        host: postgres
                        port: $POSTGRES_PORT
                        user: $POSTGRES_USER
                        password: $POSTGRES_PASSWORD
                        connectionLimit: 15
networks:
    uxbackend_network:
        driver: bridge
